spring:
  datasource:
    username: root
    password: GUAN0310
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    #是否开启驼峰式命名映射
    map-underscore-to-camel-case: true
    #mybatis-plus自带的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除设置
  global-config:
    db-config:
      #逻辑删除是数据添啥
      logic-delete-value: 1
      #要进行逻辑删除的字段,配置之后就不用加注解了,且全局可用
      logic-delete-field: isDeleted
      #逻辑未删除填啥
      logic-not-delete-value: 0

#设置root目录下(整个系统目录下包裹依赖)的日志信息为debug级别
#springboot自带的日志
#logging:
#  level:
#    com.gzc.mp.mapper: debug

